@url_dev=http://localhost:3056/v1/api 


### signup
POST {{url_dev}}/user/signup
Content-Type: application/json
x-api-key: e99205ca91b8dcfed3fde2a3cdf63441

{
    "name": "user01",
    "email": "user01@gmail.com",
    "password": "123456"
}